import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { ChatOpenAI } from '@langchain/openai';
import { HumanMessage, AIMessage, BaseMessage, SystemMessage } from '@langchain/core/messages';
import { StructuredTool } from '@langchain/core/tools';
import { PrismaService } from '../../../../core/database/prisma.service';
import { SYSTEM_PROMPT } from '../prompts/system.prompt';
import { getAllTools } from '../tools';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const { createReactAgent } = require('@langchain/langgraph/prebuilt');

/**
 * Session memory structure for conversation history
 */
interface SessionMemory {
  messages: BaseMessage[];
  createdAt: Date;
  lastActiveAt: Date;
}

/**
 * Response interface for supervisor agent queries
 */
export interface SupervisorQueryResult {
  /** The natural language answer generated by the agent */
  answer: string;
  /** List of tool names that were invoked during query processing */
  toolsUsed: string[];
  /** Total time taken to process the query in milliseconds */
  processingTimeMs: number;
}

/**
 * SupervisorAgent - LangChain.js Agent for State Directorate AI Bot
 *
 * This service implements a supervisor agent that:
 * - Uses GPT-4o-mini as the underlying LLM
 * - Manages tool selection and execution via LangGraph's createReactAgent
 * - Maintains session-based conversation memory
 * - Processes natural language queries about students, visits, reports, etc.
 *
 * @example
 * ```typescript
 * const result = await supervisorAgent.query(
 *   "How many students are in Computer Science?",
 *   "session-123"
 * );
 * console.log(result.answer); // "There are 3,245 students..."
 * ```
 */
@Injectable()
export class SupervisorAgent implements OnModuleInit {
  private readonly logger = new Logger(SupervisorAgent.name);

  /**
   * The LangGraph React Agent
   */
  private agent: any = null;

  /**
   * Map to store conversation history for each session
   */
  private memoryStore: Map<string, SessionMemory> = new Map();

  /**
   * Maximum messages to keep in history per session
   */
  private readonly maxHistoryLength = 20;

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Lifecycle hook called when the module is initialized
   */
  async onModuleInit(): Promise<void> {
    await this.initialize();
  }

  /**
   * Initializes the LangGraph agent with:
   * - ChatOpenAI LLM configured with gpt-4o-mini
   * - All available tools from the tools module
   * - System prompt with current date context
   */
  private async initialize(): Promise<void> {
    this.logger.log('Initializing Supervisor Agent...');

    try {
      // Initialize the LLM with GPT-4o-mini
      const llm = new ChatOpenAI({
        modelName: 'gpt-4o-mini',
        temperature: 0,
        openAIApiKey: process.env.OPENAI_API_KEY,
        maxRetries: 2,
        timeout: 30000,
      });

      // Get all available tools
      const tools = getAllTools(this.prisma);
      this.logger.log(`Loaded ${tools.length} tools for the agent`);

      // Get current date for system prompt placeholders
      const currentDate = new Date();
      const currentMonth = currentDate.toLocaleString('default', {
        month: 'long',
      });
      const currentYear = currentDate.getFullYear().toString();

      // Prepare the system prompt with current date context
      const formattedSystemPrompt = SYSTEM_PROMPT.replace(
        /{currentMonth}/g,
        currentMonth,
      ).replace(/{currentYear}/g, currentYear);

      // Create the React agent using LangGraph
      this.agent = createReactAgent({
        llm,
        tools,
        messageModifier: formattedSystemPrompt,
      });

      this.logger.log('Supervisor Agent initialized successfully');
    } catch (error) {
      this.logger.error('Failed to initialize Supervisor Agent', error);
      throw error;
    }
  }

  /**
   * Processes a natural language query and returns a response
   *
   * @param input - The natural language query from the user
   * @param sessionId - Optional session identifier for conversation continuity
   * @returns Promise containing the answer, tools used, and processing time
   */
  async query(input: string, sessionId?: string): Promise<SupervisorQueryResult> {
    const startTime = Date.now();

    this.logger.debug(
      `Processing query: "${input}" (session: ${sessionId || 'none'})`,
    );

    if (!this.agent) {
      return {
        answer: 'The AI assistant is not properly initialized. Please try again later.',
        toolsUsed: [],
        processingTimeMs: Date.now() - startTime,
      };
    }

    try {
      // Get or create session memory
      let sessionMemory = sessionId ? this.memoryStore.get(sessionId) : undefined;

      if (sessionId && !sessionMemory) {
        sessionMemory = {
          messages: [],
          createdAt: new Date(),
          lastActiveAt: new Date(),
        };
        this.memoryStore.set(sessionId, sessionMemory);
        this.logger.debug(`Created new session: ${sessionId}`);
      }

      // Build messages array with history
      const messages: BaseMessage[] = sessionMemory
        ? [...sessionMemory.messages, new HumanMessage(input)]
        : [new HumanMessage(input)];

      // Execute the agent
      const result = await this.agent.invoke({
        messages,
      });

      // Extract the final answer from the result
      const resultMessages = result.messages as BaseMessage[];
      const lastMessage = resultMessages[resultMessages.length - 1];
      const answer = typeof lastMessage.content === 'string'
        ? lastMessage.content
        : JSON.stringify(lastMessage.content);

      // Extract tools used from intermediate messages
      const toolsUsed = this.extractToolsUsed(resultMessages);

      // Update session memory
      if (sessionId && sessionMemory) {
        sessionMemory.messages.push(new HumanMessage(input));
        sessionMemory.messages.push(new AIMessage(answer));
        sessionMemory.lastActiveAt = new Date();

        // Trim history if too long
        if (sessionMemory.messages.length > this.maxHistoryLength) {
          sessionMemory.messages = sessionMemory.messages.slice(-this.maxHistoryLength);
        }
      }

      const processingTimeMs = Date.now() - startTime;

      this.logger.debug(
        `Query completed in ${processingTimeMs}ms. Tools used: ${toolsUsed.join(', ') || 'none'}`,
      );

      return {
        answer,
        toolsUsed,
        processingTimeMs,
      };
    } catch (error) {
      const processingTimeMs = Date.now() - startTime;
      this.logger.error(`Query failed after ${processingTimeMs}ms`, error);

      return {
        answer:
          'I encountered an error processing your query. Please try again or rephrase your question.',
        toolsUsed: [],
        processingTimeMs,
      };
    }
  }

  /**
   * Extracts unique tool names from the agent's messages
   */
  private extractToolsUsed(messages: BaseMessage[]): string[] {
    const toolNames: string[] = [];

    for (const message of messages) {
      // Check for tool calls in AI messages
      if (message.additional_kwargs?.tool_calls) {
        const toolCalls = message.additional_kwargs.tool_calls as Array<{
          function?: { name?: string };
        }>;
        for (const call of toolCalls) {
          if (call.function?.name) {
            toolNames.push(call.function.name);
          }
        }
      }
    }

    return [...new Set(toolNames)];
  }

  /**
   * Clears the conversation memory for a specific session
   */
  clearSession(sessionId: string): boolean {
    const existed = this.memoryStore.has(sessionId);
    if (existed) {
      this.memoryStore.delete(sessionId);
      this.logger.debug(`Cleared memory for session: ${sessionId}`);
    }
    return existed;
  }

  /**
   * Gets the number of active sessions
   */
  getActiveSessionCount(): number {
    return this.memoryStore.size;
  }

  /**
   * Clears all sessions from the memory store
   */
  clearAllSessions(): void {
    const count = this.memoryStore.size;
    this.memoryStore.clear();
    this.logger.log(`Cleared all ${count} sessions from memory`);
  }
}
