import { ReportDefinition } from '../interfaces/report-definition.interface';

export const complianceReportDefinitions: Record<string, ReportDefinition> = {
  'faculty-visit-compliance': {
    type: 'faculty-visit-compliance',
    name: 'Faculty Visit Compliance',
    description: 'Track faculty visit compliance for internship monitoring (per student)',
    category: 'Compliance',
    icon: 'schedule',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'companyAddress', label: 'Company Address', type: 'string', default: true },
      { id: 'reportMonth', label: 'Report Month', type: 'string', default: true, sortable: true },
      { id: 'jan', label: 'Jan', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'feb', label: 'Feb', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'mar', label: 'Mar', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'apr', label: 'Apr', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'may', label: 'May', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'jun', label: 'Jun', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'jul', label: 'Jul', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'aug', label: 'Aug', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'sep', label: 'Sep', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'oct', label: 'Oct', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'nov', label: 'Nov', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'dec', label: 'Dec', type: 'number', default: true, sortable: true, description: '0 = no visit submitted, 1 = visit submitted' },
      { id: 'internshipStartDate', label: 'Internship Start', type: 'date', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'requiredVisits', label: 'Required Visits', type: 'number', default: true },
      { id: 'completedVisits', label: 'Completed Visits', type: 'number', default: true, sortable: true },
      { id: 'pendingVisits', label: 'Pending Visits', type: 'number', default: true, sortable: true },
      { id: 'compliancePercent', label: 'Compliance %', type: 'number', default: true, sortable: true },
      { id: 'lastVisitDate', label: 'Last Visit Date', type: 'date', default: true },
      { id: 'lastVisitType', label: 'Visit Type', type: 'string', default: true, sortable: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: true },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
      { id: 'internshipStartDate', label: 'Internship Start Date (Before)', type: 'date', required: false },
    ],
    groupBy: ['institutionName', 'branchName', 'mentorName', 'complianceLevel', 'reportMonth'],
    sortableColumns: ['studentName', 'mentorName', 'completedVisits', 'pendingVisits', 'compliancePercent', 'internshipStartDate', 'institutionName', 'reportMonth'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'monthly-report-compliance': {
    type: 'monthly-report-compliance',
    name: 'Monthly Report Compliance',
    description: 'Student monthly report submission compliance',
    category: 'Compliance',
    icon: 'file-done',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'reportMonth', label: 'Report Month', type: 'string', default: true, sortable: true },
      { id: 'jan', label: 'Jan', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'feb', label: 'Feb', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'mar', label: 'Mar', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'apr', label: 'Apr', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'may', label: 'May', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'jun', label: 'Jun', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'jul', label: 'Jul', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'aug', label: 'Aug', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'sep', label: 'Sep', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'oct', label: 'Oct', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'nov', label: 'Nov', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'dec', label: 'Dec', type: 'number', default: true, sortable: true, description: '0 = no report submitted, 1 = report submitted' },
      { id: 'totalReportsExpected', label: 'Expected Reports', type: 'number', default: true },
      { id: 'reportsSubmitted', label: 'Submitted', type: 'number', default: true, sortable: true },
      { id: 'reportsApproved', label: 'Approved', type: 'number', default: true },
      { id: 'reportsPending', label: 'Pending', type: 'number', default: true, sortable: true },
      { id: 'compliancePercent', label: 'Compliance %', type: 'number', default: true, sortable: true },
      { id: 'lastSubmissionDate', label: 'Last Submission', type: 'date', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: true },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Student Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['branchName', 'mentorName', 'institutionName', 'reportMonth'],
    sortableColumns: ['studentName', 'reportsSubmitted', 'reportsPending', 'compliancePercent', 'institutionName', 'reportMonth'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'joining-report-status': {
    type: 'joining-report-status',
    name: 'Joining Report Status',
    description: 'Track joining letter/report submission status',
    category: 'Compliance',
    icon: 'file-add',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'reportMonth', label: 'Report Month', type: 'string', default: true, sortable: true },
      { id: 'internshipStartDate', label: 'Internship Start', type: 'date', default: true },
      { id: 'joiningLetterStatus', label: 'Joining Letter Status', type: 'string', default: true },
      { id: 'joiningLetterSubmittedAt', label: 'Submitted At', type: 'date', default: true },
      { id: 'joiningLetterApprovedAt', label: 'Approved At', type: 'date', default: false },
      { id: 'daysSinceStart', label: 'Days Since Start', type: 'number', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true, description: 'Combined student and user active status' },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false, description: 'User account active status' },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: true },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Student Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
      { id: 'joiningLetterStatus', label: 'Status', type: 'select', required: false, options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Submitted', value: 'SUBMITTED' },
        { label: 'Approved', value: 'APPROVED' },
        { label: 'Rejected', value: 'REJECTED' },
      ]},
    ],
    groupBy: ['branchName', 'joiningLetterStatus', 'institutionName'],
    sortableColumns: ['studentName', 'internshipStartDate', 'daysSinceStart', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'faculty-visit-details': {
    type: 'faculty-visit-details',
    name: 'Faculty Visit Details',
    description: 'Detailed faculty visit logs with observations and feedback',
    category: 'Compliance',
    icon: 'file-search',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'TEACHER', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'reportMonth', label: 'Report Month', type: 'string', default: true, sortable: true },
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'companyAddress', label: 'Company Address', type: 'string', default: true },
      { id: 'companyContact', label: 'Company Contact', type: 'string', default: true },
      { id: 'visitDone', label: 'Visit Done', type: 'boolean', default: true },
      { id: 'visitDate', label: 'Visit Date', type: 'date', default: true, sortable: true },
      { id: 'visitType', label: 'Visit Type', type: 'string', default: true },
      { id: 'visitLocation', label: 'Visit Location', type: 'string', default: true },
      { id: 'visitNumber', label: 'Visit Number', type: 'number', default: true },
      { id: 'visitStatus', label: 'Visit Status', type: 'string', default: true },
      { id: 'titleOfProjectWork', label: 'Title of Project Work', type: 'string', default: true },
      { id: 'assistanceRequiredFromInstitute', label: 'Assistance Required', type: 'string', default: true },
      { id: 'responseFromOrganisation', label: 'Response from Organisation', type: 'string', default: false },
      { id: 'remarksOfOrganisationSupervisor', label: 'Supervisor Remarks', type: 'string', default: false },
      { id: 'significantChangeInPlan', label: 'Significant Change in Plan', type: 'string', default: false },
      { id: 'observationsAboutStudent', label: 'Observations About Student', type: 'string', default: true },
      { id: 'feedbackSharedWithStudent', label: 'Feedback Shared', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: true },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
      { id: 'visitType', label: 'Visit Type', type: 'select', required: false, options: [
        { label: 'Physical', value: 'PHYSICAL' },
        { label: 'Virtual', value: 'VIRTUAL' },
        { label: 'Telephonic', value: 'TELEPHONIC' },
      ]},
      { id: 'visitStatus', label: 'Visit Status', type: 'select', required: false, options: [
        { label: 'Scheduled', value: 'SCHEDULED' },
        { label: 'In Progress', value: 'IN_PROGRESS' },
        { label: 'Completed', value: 'COMPLETED' },
        { label: 'Cancelled', value: 'CANCELLED' },
      ]},
      { id: 'dateRange', label: 'Visit Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['institutionName', 'branchName', 'mentorName', 'visitType', 'visitStatus', 'reportMonth'],
    sortableColumns: ['mentorName', 'studentName', 'visitDate', 'institutionName', 'reportMonth'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },
};
