import { ReportDefinition } from '../interfaces/report-definition.interface';

export const trainingReportDefinitions: Record<string, ReportDefinition> = {
	'training-feedback-responses': {
		type: 'training-feedback-responses',
		name: 'Training Feedback Responses',
		description: 'Feedback responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'comment',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'institutionName'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-pre-test-responses': {
		type: 'training-pre-test-responses',
		name: 'Training Pre-Test Responses',
		description: 'Pre-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-post-test-responses': {
		type: 'training-post-test-responses',
		name: 'Training Post-Test Responses',
		description: 'Post-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-wise-summary': {
		type: 'training-wise-summary',
		name: 'Training-wise Summary Report',
		description: 'Summary report showing training details with participant counts, attendance, pre-test, post-test, feedback, and lesson plan statistics',
		category: 'Training',
		icon: 'chart-bar',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'totalDays', label: 'Total Days', type: 'number', default: true, sortable: true },
			{ id: 'totalHours', label: 'Total Hours', type: 'number', default: true, sortable: true },
			{ id: 'startDate', label: 'Start Date', type: 'date', default: true, sortable: true },
			{ id: 'endDate', label: 'End Date', type: 'date', default: true, sortable: true },
			{ id: 'course', label: 'Course/Target Branches', type: 'string', default: true, sortable: false },
			{ id: 'deliveryMode', label: 'Delivery Mode', type: 'string', default: true, sortable: true },
			{ id: 'totalParticipants', label: 'Total Participants', type: 'number', default: true, sortable: true },
			{ id: 'attendanceCount', label: 'Attendance Filled', type: 'number', default: true, sortable: true },
			{ id: 'attendancePercentage', label: 'Attendance %', type: 'number', default: true, sortable: true },
			{ id: 'preTestFilledCount', label: 'Pre-Test Filled', type: 'number', default: true, sortable: true },
			{ id: 'preTestPercentage', label: 'Pre-Test %', type: 'number', default: true, sortable: true },
			{ id: 'postTestFilledCount', label: 'Post-Test Filled', type: 'number', default: true, sortable: true },
			{ id: 'postTestPercentage', label: 'Post-Test %', type: 'number', default: true, sortable: true },
			{ id: 'feedbackFilledCount', label: 'Feedback Filled', type: 'number', default: true, sortable: true },
			{ id: 'feedbackPercentage', label: 'Feedback %', type: 'number', default: true, sortable: true },
			{ id: 'lessonPlanFilledCount', label: 'Lesson Plan Filled', type: 'number', default: true, sortable: true },
			{ id: 'lessonPlanPercentage', label: 'Lesson Plan %', type: 'number', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
			{ id: 'deliveryMode', label: 'Delivery Mode', type: 'select', required: false, options: [
				{ value: 'OFFLINE', label: 'Offline' },
				{ value: 'ONLINE', label: 'Online' },
				{ value: 'HYBRID', label: 'Hybrid' },
			]},
		],
		groupBy: ['trainingName', 'deliveryMode'],
		sortableColumns: ['trainingName', 'startDate', 'endDate', 'totalParticipants', 'attendanceCount', 'preTestFilledCount', 'postTestFilledCount', 'feedbackFilledCount', 'lessonPlanFilledCount'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-non-compliance': {
		type: 'training-non-compliance',
		name: 'Training Non-Compliance Report',
		description: 'Faculty details who have not filled out attendance, pre-test, post-test, feedback form, or lesson plan - organized by college and course',
		category: 'Training',
		icon: 'alert-triangle',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyEmail', label: 'Email', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true, sortable: false },
			{ id: 'institutionName', label: 'Institution/College', type: 'string', default: true, sortable: true },
			{ id: 'branchName', label: 'Branch/Course', type: 'string', default: true, sortable: true },
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'attendanceFilled', label: 'Attendance', type: 'boolean', default: true, sortable: true },
			{ id: 'preTestFilled', label: 'Pre-Test', type: 'boolean', default: true, sortable: true },
			{ id: 'postTestFilled', label: 'Post-Test', type: 'boolean', default: true, sortable: true },
			{ id: 'feedbackFilled', label: 'Feedback', type: 'boolean', default: true, sortable: true },
			{ id: 'lessonPlanFilled', label: 'Lesson Plan', type: 'boolean', default: true, sortable: true },
			{ id: 'missingItems', label: 'Missing Items', type: 'string', default: true, sortable: false },
			{ id: 'missingCount', label: 'Missing Count', type: 'number', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
			{ id: 'nonComplianceType', label: 'Non-Compliance Type', type: 'multiSelect', required: false, options: [
				{ value: 'attendance', label: 'Missing Attendance' },
				{ value: 'preTest', label: 'Missing Pre-Test' },
				{ value: 'postTest', label: 'Missing Post-Test' },
				{ value: 'feedback', label: 'Missing Feedback' },
				{ value: 'lessonPlan', label: 'Missing Lesson Plan' },
			]},
		],
		groupBy: ['institutionName', 'branchName', 'trainingName'],
		sortableColumns: ['facultyName', 'institutionName', 'branchName', 'trainingName', 'trainingStartDate', 'missingCount'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-test-comparison': {
		type: 'training-test-comparison',
		name: 'Pre & Post Test Comparison Report',
		description: 'Compare faculty performance between pre-test and post-test to measure learning effectiveness and improvement',
		category: 'Training',
		icon: 'rise',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'email', label: 'Email', type: 'string', default: true, sortable: true },
			{ id: 'phone', label: 'Phone', type: 'string', default: true, sortable: false },
			{ id: 'department', label: 'Department', type: 'string', default: true, sortable: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'trainingTitle', label: 'Training', type: 'string', default: true, sortable: true },
			{ id: 'preTestScore', label: 'Pre-Test Score (%)', type: 'number', default: true, sortable: true },
			{ id: 'postTestScore', label: 'Post-Test Score (%)', type: 'number', default: true, sortable: true },
			{ id: 'improvement', label: 'Improvement (%)', type: 'number', default: true, sortable: true },
			{ id: 'performanceCategory', label: 'Performance Category', type: 'string', default: true, sortable: true },
			{ id: 'preTestDate', label: 'Pre-Test Date', type: 'date', default: true, sortable: true },
			{ id: 'postTestDate', label: 'Post-Test Date', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingTitle', 'institutionName', 'department', 'performanceCategory'],
		sortableColumns: ['facultyName', 'institutionName', 'trainingTitle', 'preTestScore', 'postTestScore', 'improvement'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-wise-compliance': {
		type: 'training-wise-compliance',
		name: 'Training-wise Compliance Report',
		description: 'Multi-sheet Excel report with one sheet per training showing all participants and their compliance status for attendance, tests, feedback, and lesson plans',
		category: 'Training',
		icon: 'check-square',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingId', label: 'Training ID', type: 'string', default: false, sortable: false },
			{ id: 'trainingTitle', label: 'Training', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'email', label: 'Email', type: 'string', default: true, sortable: true },
			{ id: 'phone', label: 'Phone', type: 'string', default: true, sortable: false },
			{ id: 'department', label: 'Department', type: 'string', default: true, sortable: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'attendanceStatus', label: 'Attendance', type: 'string', default: true, sortable: true },
			{ id: 'preTestStatus', label: 'Pre-Test', type: 'string', default: true, sortable: true },
			{ id: 'postTestStatus', label: 'Post-Test', type: 'string', default: true, sortable: true },
			{ id: 'feedbackStatus', label: 'Feedback', type: 'string', default: true, sortable: true },
			{ id: 'lessonPlanStatus', label: 'Lesson Plan', type: 'string', default: true, sortable: true },
			{ id: 'completedItems', label: 'Completed Items', type: 'number', default: true, sortable: true },
			{ id: 'totalItems', label: 'Total Items', type: 'number', default: true, sortable: false },
			{ id: 'compliancePercentage', label: 'Compliance %', type: 'number', default: true, sortable: true },
			{ id: 'complianceStatus', label: 'Status', type: 'string', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingTitle', 'institutionName', 'complianceStatus'],
		sortableColumns: ['trainingTitle', 'facultyName', 'institutionName', 'compliancePercentage'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-feedback-analysis': {
		type: 'training-feedback-analysis',
		name: 'Training Feedback Analysis Report',
		description: 'Aggregate insights and analytics from feedback responses - rating distribution, question insights, satisfaction metrics, and NPS scores',
		category: 'Training',
		icon: 'bar-chart',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingTitle', label: 'Training', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'End Date', type: 'date', default: true, sortable: true },
			{ id: 'totalParticipants', label: 'Total Participants', type: 'number', default: true, sortable: true },
			{ id: 'totalFeedbackResponses', label: 'Feedback Responses', type: 'number', default: true, sortable: true },
			{ id: 'responseRate', label: 'Response Rate %', type: 'number', default: true, sortable: true },
			// Rating Distribution
			{ id: 'totalRatings', label: 'Total Ratings', type: 'number', default: true, sortable: true },
			{ id: 'rating5Count', label: 'Rating 5 (Count)', type: 'number', default: true, sortable: true },
			{ id: 'rating5Pct', label: 'Rating 5 (%)', type: 'number', default: true, sortable: true },
			{ id: 'rating4Count', label: 'Rating 4 (Count)', type: 'number', default: true, sortable: true },
			{ id: 'rating4Pct', label: 'Rating 4 (%)', type: 'number', default: true, sortable: true },
			{ id: 'rating3Count', label: 'Rating 3 (Count)', type: 'number', default: true, sortable: true },
			{ id: 'rating3Pct', label: 'Rating 3 (%)', type: 'number', default: true, sortable: true },
			{ id: 'rating2Count', label: 'Rating 2 (Count)', type: 'number', default: false, sortable: true },
			{ id: 'rating2Pct', label: 'Rating 2 (%)', type: 'number', default: false, sortable: true },
			{ id: 'rating1Count', label: 'Rating 1 (Count)', type: 'number', default: false, sortable: true },
			{ id: 'rating1Pct', label: 'Rating 1 (%)', type: 'number', default: false, sortable: true },
			// Question-level Insights
			{ id: 'highestRatedQuestion', label: 'Highest Rated Question', type: 'string', default: true, sortable: false },
			{ id: 'highestRatedAvg', label: 'Highest Rating Avg', type: 'number', default: true, sortable: true },
			{ id: 'lowestRatedQuestion', label: 'Lowest Rated Question', type: 'string', default: true, sortable: false },
			{ id: 'lowestRatedAvg', label: 'Lowest Rating Avg', type: 'number', default: true, sortable: true },
			// Category Averages
			{ id: 'avgOverallSatisfaction', label: 'Avg Rating Q1 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgContentQuality', label: 'Avg Rating Q2 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgTrainerKnowledge', label: 'Avg Rating Q3 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgTrainerCommunication', label: 'Avg Rating Q4 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgMaterialsQuality', label: 'Avg Rating Q5 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgPracticalRelevance', label: 'Avg Rating Q6 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgTimeManagement', label: 'Avg Rating Q7 (1-5)', type: 'number', default: false, sortable: true },
			{ id: 'avgRecommendTraining', label: 'Avg Rating Q8 (1-5)', type: 'number', default: false, sortable: true },
			// Expectation Distribution
			{ id: 'expectationFullyMet', label: 'Expectations Fully Met', type: 'number', default: true, sortable: true },
			{ id: 'expectationPartiallyMet', label: 'Expectations Partially Met', type: 'number', default: true, sortable: true },
			{ id: 'expectationNotMet', label: 'Expectations Not Met', type: 'number', default: true, sortable: true },
			// Overall Metrics
			{ id: 'npsScore', label: 'NPS Score', type: 'number', default: true, sortable: true },
			{ id: 'overallAvgRating', label: 'Overall Rating (1-5)', type: 'number', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingTitle'],
		sortableColumns: ['trainingTitle', 'totalParticipants', 'responseRate', 'totalRatings', 'rating5Pct', 'highestRatedAvg', 'lowestRatedAvg', 'npsScore', 'overallAvgRating'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},
};
