import { ReportDefinition } from '../interfaces/report-definition.interface';

export const trainingReportDefinitions: Record<string, ReportDefinition> = {
	'training-feedback-responses': {
		type: 'training-feedback-responses',
		name: 'Training Feedback Responses',
		description: 'Feedback responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'comment',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'institutionName'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-pre-test-responses': {
		type: 'training-pre-test-responses',
		name: 'Training Pre-Test Responses',
		description: 'Pre-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-post-test-responses': {
		type: 'training-post-test-responses',
		name: 'Training Post-Test Responses',
		description: 'Post-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},
};
