import { ReportDefinition } from '../interfaces/report-definition.interface';

export const trainingReportDefinitions: Record<string, ReportDefinition> = {
	'training-feedback-responses': {
		type: 'training-feedback-responses',
		name: 'Training Feedback Responses',
		description: 'Feedback responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'comment',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'institutionName'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-pre-test-responses': {
		type: 'training-pre-test-responses',
		name: 'Training Pre-Test Responses',
		description: 'Pre-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-post-test-responses': {
		type: 'training-post-test-responses',
		name: 'Training Post-Test Responses',
		description: 'Post-test responses submitted by faculty for trainings',
		category: 'Training',
		icon: 'form',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyBranch', label: 'Branch', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true },
			{ id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
			{ id: 'score', label: 'Score', type: 'number', default: true, sortable: true },
			{ id: 'passed', label: 'Passed', type: 'boolean', default: true, sortable: true },
			{ id: 'submittedAt', label: 'Submitted At', type: 'date', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training ID', type: 'text', required: false, placeholder: 'Training UUID' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
		],
		groupBy: ['trainingName', 'institutionName', 'facultyBranch'],
		sortableColumns: ['trainingName', 'trainingStartDate', 'trainingEndDate', 'facultyName', 'score', 'submittedAt'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-wise-summary': {
		type: 'training-wise-summary',
		name: 'Training-wise Summary Report',
		description: 'Summary report showing training details with participant counts, attendance, pre-test, post-test, feedback, and lesson plan statistics',
		category: 'Training',
		icon: 'chart-bar',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'duration', label: 'Duration (Hours)', type: 'number', default: true, sortable: true },
			{ id: 'startDate', label: 'Start Date', type: 'date', default: true, sortable: true },
			{ id: 'endDate', label: 'End Date', type: 'date', default: true, sortable: true },
			{ id: 'course', label: 'Course/Target Branches', type: 'string', default: true, sortable: false },
			{ id: 'deliveryMode', label: 'Delivery Mode', type: 'string', default: true, sortable: true },
			{ id: 'totalParticipants', label: 'Total Participants', type: 'number', default: true, sortable: true },
			{ id: 'attendanceCount', label: 'Attendance Filled', type: 'number', default: true, sortable: true },
			{ id: 'attendancePercentage', label: 'Attendance %', type: 'number', default: true, sortable: true },
			{ id: 'preTestFilledCount', label: 'Pre-Test Filled', type: 'number', default: true, sortable: true },
			{ id: 'preTestPercentage', label: 'Pre-Test %', type: 'number', default: true, sortable: true },
			{ id: 'postTestFilledCount', label: 'Post-Test Filled', type: 'number', default: true, sortable: true },
			{ id: 'postTestPercentage', label: 'Post-Test %', type: 'number', default: true, sortable: true },
			{ id: 'feedbackFilledCount', label: 'Feedback Filled', type: 'number', default: true, sortable: true },
			{ id: 'feedbackPercentage', label: 'Feedback %', type: 'number', default: true, sortable: true },
			{ id: 'lessonPlanFilledCount', label: 'Lesson Plan Filled', type: 'number', default: true, sortable: true },
			{ id: 'lessonPlanPercentage', label: 'Lesson Plan %', type: 'number', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
			{ id: 'deliveryMode', label: 'Delivery Mode', type: 'select', required: false, options: [
				{ value: 'OFFLINE', label: 'Offline' },
				{ value: 'ONLINE', label: 'Online' },
				{ value: 'HYBRID', label: 'Hybrid' },
			]},
		],
		groupBy: ['trainingName', 'deliveryMode'],
		sortableColumns: ['trainingName', 'startDate', 'endDate', 'totalParticipants', 'attendanceCount', 'preTestFilledCount', 'postTestFilledCount', 'feedbackFilledCount', 'lessonPlanFilledCount'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},

	'training-non-compliance': {
		type: 'training-non-compliance',
		name: 'Training Non-Compliance Report',
		description: 'Faculty details who have not filled out attendance, pre-test, post-test, feedback form, or lesson plan - organized by college and course',
		category: 'Training',
		icon: 'alert-triangle',
		availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
		columns: [
			{ id: 'facultyName', label: 'Faculty Name', type: 'string', default: true, sortable: true },
			{ id: 'facultyEmail', label: 'Email', type: 'string', default: true, sortable: true },
			{ id: 'facultyPhone', label: 'Phone', type: 'string', default: true, sortable: false },
			{ id: 'institutionName', label: 'Institution/College', type: 'string', default: true, sortable: true },
			{ id: 'branchName', label: 'Branch/Course', type: 'string', default: true, sortable: true },
			{ id: 'trainingName', label: 'Training Name', type: 'string', default: true, sortable: true },
			{ id: 'trainingStartDate', label: 'Training Start Date', type: 'date', default: true, sortable: true },
			{ id: 'trainingEndDate', label: 'Training End Date', type: 'date', default: true, sortable: true },
			{ id: 'attendanceFilled', label: 'Attendance', type: 'boolean', default: true, sortable: true },
			{ id: 'preTestFilled', label: 'Pre-Test', type: 'boolean', default: true, sortable: true },
			{ id: 'postTestFilled', label: 'Post-Test', type: 'boolean', default: true, sortable: true },
			{ id: 'feedbackFilled', label: 'Feedback', type: 'boolean', default: true, sortable: true },
			{ id: 'lessonPlanFilled', label: 'Lesson Plan', type: 'boolean', default: true, sortable: true },
			{ id: 'missingItems', label: 'Missing Items', type: 'string', default: true, sortable: false },
			{ id: 'missingCount', label: 'Missing Count', type: 'number', default: true, sortable: true },
		],
		filters: [
			{ id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
			{ id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
			{ id: 'trainingId', label: 'Training', type: 'select', dynamic: true, required: false, placeholder: 'All Trainings' },
			{ id: 'dateRange', label: 'Training Date Range', type: 'dateRange', required: false },
			{ id: 'nonComplianceType', label: 'Non-Compliance Type', type: 'multiSelect', required: false, options: [
				{ value: 'attendance', label: 'Missing Attendance' },
				{ value: 'preTest', label: 'Missing Pre-Test' },
				{ value: 'postTest', label: 'Missing Post-Test' },
				{ value: 'feedback', label: 'Missing Feedback' },
				{ value: 'lessonPlan', label: 'Missing Lesson Plan' },
			]},
		],
		groupBy: ['institutionName', 'branchName', 'trainingName'],
		sortableColumns: ['facultyName', 'institutionName', 'branchName', 'trainingName', 'trainingStartDate', 'missingCount'],
		exportFormats: ['excel', 'csv', 'pdf', 'json'],
	},
};
