import { ReportDefinition } from '../interfaces/report-definition.interface';

export const internshipReportDefinitions: Record<string, ReportDefinition> = {
  'internship-by-institution': {
    type: 'internship-by-institution',
    name: 'Internships by Institution',
    description: 'Institution-wise internship distribution',
    category: 'Internship',
    icon: 'bank',
    availableFor: ['STATE_DIRECTORATE', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true, sortable: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'pendingApplications', label: 'Pending', type: 'number', default: true },
      { id: 'totalSubmittedVisits', label: 'Submitted Visits', type: 'number', default: true },
      { id: 'totalSubmittedReports', label: 'Submitted Reports', type: 'number', default: true },
      { id: 'totalJoiningLetters', label: 'Joining Report', type: 'number', default: true },
      { id: 'internshipRate', label: 'Internship Rate %', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'startDateRange', label: 'Internship Start Date Range', type: 'dateRange', required: false },
    ],
    groupBy: [],
    sortableColumns: ['institutionName', 'totalStudents', 'activeInternships', 'internshipRate'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'self-identified-internships': {
    type: 'self-identified-internships',
    name: 'Self-Identified Internships',
    description: 'Internships identified by students themselves',
    category: 'Internship',
    icon: 'user-add',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'phoneNumber', label: 'Phone Number', type: 'string', default: true },
      { id: 'email', label: 'Email', type: 'string', default: false },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true, sortable: true },
      { id: 'companyCity', label: 'Company City', type: 'string', default: true },
      { id: 'companyAddress', label: 'Company Address', type: 'string', default: false },
      { id: 'companyContact', label: 'Company Contact', type: 'string', default: true },
      { id: 'companyEmail', label: 'Company Email', type: 'string', default: false },
      { id: 'hrName', label: 'HR Name', type: 'string', default: true },
      { id: 'hrDesignation', label: 'HR Designation', type: 'string', default: false },
      { id: 'hrContact', label: 'HR Contact', type: 'string', default: true },
      { id: 'hrEmail', label: 'HR Email', type: 'string', default: false },
      { id: 'jobProfile', label: 'Job Profile', type: 'string', default: true },
      { id: 'stipend', label: 'Stipend', type: 'number', default: true },
      { id: 'status', label: 'Status', type: 'string', default: true },
      { id: 'internshipStatus', label: 'Internship Status', type: 'string', default: false },
      { id: 'appliedDate', label: 'Applied Date', type: 'date', default: true, sortable: true },
      { id: 'startDate', label: 'Start Date', type: 'date', default: true, sortable: true },
      { id: 'endDate', label: 'End Date', type: 'date', default: true },
      { id: 'duration', label: 'Duration', type: 'string', default: false },
      { id: 'verificationStatus', label: 'Verification', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'mentorEmail', label: 'Mentor Email', type: 'string', default: false },
      { id: 'mentorPhone', label: 'Mentor Phone', type: 'string', default: false },
      { id: 'joiningLetterStatus', label: 'Joining Letter', type: 'string', default: true, description: 'Joining letter submission status (Submitted/Pending)' },
      { id: 'applicationFillRate', label: 'Application Fill Rate %', type: 'number', default: true, description: 'Percentage of internship application details filled' },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true, description: 'Combined student and user active status' },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false, description: 'User account active status' },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: true },
      { id: 'institutionName', label: 'Institution Name', type: 'text', required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Student Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
      { id: 'verificationStatus', label: 'Verification Status', type: 'select', required: false, options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Verified', value: 'VERIFIED' },
        { label: 'Rejected', value: 'REJECTED' },
      ]},
      { id: 'dateRange', label: 'Applied Date Range', type: 'dateRange', required: false },
      { id: 'startDateRange', label: 'Start Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['branchName', 'verificationStatus', 'status', 'institutionName'],
    sortableColumns: ['studentName', 'companyName', 'appliedDate', 'startDate', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },
};
