import { ReportDefinition } from '../interfaces/report-definition.interface';

export const principalReportDefinitions: Record<string, ReportDefinition> = {
  'principal-visit-logs': {
    type: 'principal-visit-logs',
    name: 'Principal Visit Logs',
    description: 'Detailed report of principal visit logs with student feedback',
    category: 'Principal',
    icon: 'audit',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'visitDate', label: 'Visit Date', type: 'date', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'principalName', label: 'Principal Name', type: 'string', default: true, sortable: true },
      { id: 'companyNames', label: 'Companies', type: 'string', default: true },
      { id: 'visitType', label: 'Visit Type', type: 'string', default: true, sortable: true },
      { id: 'visitLocation', label: 'Location', type: 'string', default: true },
      { id: 'status', label: 'Status', type: 'string', default: true, sortable: true },
      { id: 'responseFromOrganisation', label: 'Response From Organisation', type: 'string', default: true },
      { id: 'observationsAboutIndustry', label: 'Observations About Industry', type: 'string', default: true },
      { id: 'followUpRequired', label: 'Follow-up Required', type: 'boolean', default: true },
      { id: 'nextVisitDate', label: 'Next Visit Date', type: 'date', default: false },
      { id: 'attendanceStatus', label: 'Attendance Status', type: 'string', default: true },
      { id: 'createdAt', label: 'Created At', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'principalId', label: 'Principal', type: 'select', dynamic: true, required: false },
      { id: 'status', label: 'Status', type: 'select', required: false, options: [
        { label: 'Draft', value: 'DRAFT' },
        { label: 'Completed', value: 'COMPLETED' },
      ]},
      { id: 'visitType', label: 'Visit Type', type: 'select', required: false, options: [
        { label: 'Physical', value: 'PHYSICAL' },
        { label: 'Virtual', value: 'VIRTUAL' },
        { label: 'Telephonic', value: 'TELEPHONIC' },
      ]},
      { id: 'followUpRequired', label: 'Follow-up Required', type: 'boolean', required: false },
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['institutionName', 'principalName', 'visitType', 'status'],
    sortableColumns: ['visitDate', 'institutionName', 'principalName', 'visitType', 'status'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'principal-visit-summary': {
    type: 'principal-visit-summary',
    name: 'Principal Visit Summary',
    description: 'Summary statistics of principal visits by institution',
    category: 'Principal',
    icon: 'bar-chart',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'principalName', label: 'Principal Name', type: 'string', default: true, sortable: true },
      { id: 'totalVisits', label: 'Total Visits', type: 'number', default: true, sortable: true },
      { id: 'physicalVisits', label: 'Physical Visits', type: 'number', default: true },
      { id: 'virtualVisits', label: 'Virtual Visits', type: 'number', default: true },
      { id: 'telephonicVisits', label: 'Telephonic Visits', type: 'number', default: true },
      { id: 'completedVisitLogs', label: 'Completed Visit Logs', type: 'number', default: true },
      { id: 'draftVisits', label: 'Drafts', type: 'number', default: true },
      { id: 'avgSatisfactionRating', label: 'Avg Satisfaction Rating', type: 'number', default: true, sortable: true },
      { id: 'studentsVisited', label: 'Students Visited', type: 'number', default: true },
      { id: 'followUpsRequired', label: 'Follow-ups Required', type: 'number', default: true },
      { id: 'lastVisitDate', label: 'Last Visit Date', type: 'date', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['institutionName'],
    sortableColumns: ['institutionName', 'principalName', 'totalVisits', 'completedVisitLogs', 'avgSatisfactionRating'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },
};
