import { ReportDefinition } from '../interfaces/report-definition.interface';

export const studentReportDefinitions: Record<string, ReportDefinition> = {
  'student-directory': {
    type: 'student-directory',
    name: 'Student Directory',
    description: 'Complete list of all students with their details',
    category: 'Student',
    icon: 'team',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNumber', label: 'Phone', type: 'string', default: false },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'currentYear', label: 'Year', type: 'number', default: true, sortable: true },
      { id: 'currentSemester', label: 'Semester', type: 'number', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'internshipStatus', label: 'Internship Status', type: 'string', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true, description: 'Combined student and user active status' },
      { id: 'studentActive', label: 'Student Active', type: 'boolean', default: false, description: 'Student record active status' },
      { id: 'userActive', label: 'User Active', type: 'boolean', default: false, description: 'User account active status' },
      { id: 'createdAt', label: 'Registered On', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'currentYear', label: 'Year', type: 'select', required: false, options: [
        { label: '1st Year', value: 1 },
        { label: '2nd Year', value: 2 },
        { label: '3rd Year', value: 3 },
        { label: '4th Year', value: 4 },
      ]},
      { id: 'isActive', label: 'Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
    ],
    groupBy: ['branchName', 'currentYear', 'institutionName'],
    sortableColumns: ['rollNumber', 'name', 'branchName', 'currentYear', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'student-compliance': {
    type: 'student-compliance',
    name: 'Student Compliance Report',
    description: 'Track student compliance with reporting requirements',
    category: 'Student',
    icon: 'audit',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'gender', label: 'Gender', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'hasInternship', label: 'Has Internship', type: 'string', default: true },
      { id: 'joiningReportStatus', label: 'Joining Report', type: 'string', default: true },
      { id: 'monthlyReportsSubmitted', label: 'Monthly Reports', type: 'number', default: true },
      { id: 'lastReportDate', label: 'Last Report Date', type: 'date', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true, description: 'Combined student and user active status' },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false, description: 'User account active status' },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'complianceLevel', label: 'Compliance Level', type: 'select', required: false, options: [
        { label: 'Compliant (80%+)', value: 'high' },
        { label: 'Partial (50-80%)', value: 'medium' },
        { label: 'Non-Compliant (<50%)', value: 'low' },
      ]},
      { id: 'isActive', label: 'Student Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
    ],
    groupBy: ['branchName', 'mentorName', 'complianceLevel', 'institutionName'],
    sortableColumns: ['rollNumber', 'name', 'complianceScore', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'student-by-branch': {
    type: 'student-by-branch',
    name: 'Students by Branch',
    description: 'Student distribution across branches',
    category: 'Student',
    icon: 'apartment',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'pendingInternships', label: 'Pending', type: 'number', default: true },
      { id: 'placedStudents', label: 'Placed', type: 'number', default: true },
      { id: 'avgComplianceScore', label: 'Avg Compliance %', type: 'number', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
      { id: 'academicYear', label: 'Academic Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['institutionName'],
    sortableColumns: ['branchName', 'totalStudents', 'activeInternships'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'students-without-internship': {
    type: 'students-without-internship',
    name: 'Students Without Internship',
    description: 'Students who have not filled any internship application',
    category: 'Student',
    icon: 'user-delete',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: false },
      { id: 'phoneNumber', label: 'Phone', type: 'string', default: false },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'currentYear', label: 'Year', type: 'number', default: true, sortable: true },
      { id: 'currentSemester', label: 'Semester', type: 'number', default: true },
      { id: 'institutionName', label: 'College Name', type: 'string', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true, description: 'Combined student and user active status' },
      { id: 'createdAt', label: 'Registered On', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false, placeholder: 'All Institutions' },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'currentYear', label: 'Year', type: 'select', required: false, options: [
        { label: '1st Year', value: 1 },
        { label: '2nd Year', value: 2 },
        { label: '3rd Year', value: 3 },
        { label: '4th Year', value: 4 },
      ]},
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
    ],
    groupBy: ['branchName', 'currentYear', 'institutionName', 'mentorName'],
    sortableColumns: ['rollNumber', 'name', 'branchName', 'currentYear', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },
};
