import { ReportDefinition } from '../interfaces/report-definition.interface';

export const userActivityReportDefinitions: Record<string, ReportDefinition> = {
  'user-login-activity': {
    type: 'user-login-activity',
    name: 'User Login Activity Report',
    description: 'Track user login activity, password changes, and first-time logins by institution',
    category: 'User Activity',
    icon: 'login',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true, sortable: true },
      { id: 'phoneNo', label: 'Phone', type: 'string', default: false },
      { id: 'role', label: 'Role', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: false },
      { id: 'designation', label: 'Designation', type: 'string', default: false },
      { id: 'accountCreatedAt', label: 'Account Created', type: 'date', default: true, sortable: true },
      { id: 'loginCount', label: 'Login Count', type: 'number', default: true, sortable: true },
      { id: 'lastLoginAt', label: 'Last Login', type: 'date', default: true, sortable: true },
      { id: 'previousLoginAt', label: 'Previous Login', type: 'date', default: false },
      { id: 'lastLoginIp', label: 'Last Login IP', type: 'string', default: false },
      { id: 'hasChangedPassword', label: 'Password Changed', type: 'boolean', default: true },
      { id: 'passwordChangedAt', label: 'Password Changed At', type: 'date', default: false },
      { id: 'daysSinceLastLogin', label: 'Days Since Last Login', type: 'number', default: true },
      { id: 'daysSinceCreation', label: 'Days Since Creation', type: 'number', default: false },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false },
      { id: 'studentActive', label: 'Student Record Active', type: 'boolean', default: false },
      { id: 'status', label: 'Login Status', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      {
        id: 'role',
        label: 'User Role',
        type: 'multiSelect',
        required: false,
        options: [
          { value: 'STUDENT', label: 'Student' },
          { value: 'TEACHER', label: 'Teacher' },
          { value: 'FACULTY_SUPERVISOR', label: 'Faculty Supervisor' },
          { value: 'PRINCIPAL', label: 'Principal' },
          { value: 'ACCOUNTANT', label: 'Accountant' },
          { value: 'PLACEMENT_OFFICER', label: 'Placement Officer' },
          { value: 'INDUSTRY', label: 'Industry' },
          { value: 'INDUSTRY_SUPERVISOR', label: 'Industry Supervisor' },
          { value: 'STATE_DIRECTORATE', label: 'State Directorate' },
        ],
      },
      {
        id: 'loginStatus',
        label: 'Login Status',
        type: 'select',
        required: false,
        options: [
          { value: 'logged_in', label: 'Has Logged In' },
          { value: 'never_logged_in', label: 'Never Logged In' },
        ],
      },
      {
        id: 'passwordStatus',
        label: 'Password Status',
        type: 'select',
        required: false,
        options: [
          { value: 'changed', label: 'Changed Password' },
          { value: 'default', label: 'Using Default Password' },
        ],
      },
      {
        id: 'activityStatus',
        label: 'Activity Status',
        type: 'select',
        required: false,
        options: [
          { value: 'active_7', label: 'Active (Last 7 days)' },
          { value: 'active_30', label: 'Active (Last 30 days)' },
          { value: 'inactive_30', label: 'Inactive (30+ days)' },
          { value: 'inactive_90', label: 'Inactive (90+ days)' },
        ],
      },
      { id: 'isActive', label: 'Account Status', type: 'select', required: false, options: [
        { label: 'Active Accounts', value: true },
        { label: 'Inactive Accounts', value: false },
      ]},
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['institutionName', 'role', 'status'],
    sortableColumns: ['userName', 'email', 'role', 'loginCount', 'lastLoginAt', 'accountCreatedAt', 'daysSinceLastLogin'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'user-session-history': {
    type: 'user-session-history',
    name: 'User Session History',
    description: 'Detailed session history including IP addresses, devices, and session duration',
    category: 'User Activity',
    icon: 'history',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'role', label: 'Role', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'sessionStartedAt', label: 'Session Started', type: 'date', default: true, sortable: true },
      { id: 'lastActivityAt', label: 'Last Activity', type: 'date', default: true },
      { id: 'sessionDuration', label: 'Duration (mins)', type: 'number', default: true },
      { id: 'ipAddress', label: 'IP Address', type: 'string', default: true },
      { id: 'userAgent', label: 'Browser/Device', type: 'string', default: false },
      { id: 'deviceInfo', label: 'Device Info', type: 'string', default: false },
      { id: 'isActive', label: 'Session Active', type: 'boolean', default: true },
      { id: 'isUserActive', label: 'User Active', type: 'boolean', default: false },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false },
      { id: 'studentActive', label: 'Student Record Active', type: 'boolean', default: false },
      { id: 'expiresAt', label: 'Expires At', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'userId', label: 'User', type: 'select', dynamic: true, required: false },
      { id: 'role', label: 'Role', type: 'select', required: false, options: [
        { value: 'STUDENT', label: 'Student' },
        { value: 'TEACHER', label: 'Teacher' },
        { value: 'FACULTY_SUPERVISOR', label: 'Faculty Supervisor' },
        { value: 'PRINCIPAL', label: 'Principal' },
        { value: 'INDUSTRY', label: 'Industry' },
      ]},
      { id: 'sessionStatus', label: 'Session Status', type: 'select', required: false, options: [
        { value: 'active', label: 'Active Sessions' },
        { value: 'expired', label: 'Expired Sessions' },
        { value: 'invalidated', label: 'Invalidated Sessions' },
      ]},
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['userName', 'role', 'institutionName'],
    sortableColumns: ['userName', 'sessionStartedAt', 'lastActivityAt', 'sessionDuration'],
    exportFormats: ['excel', 'csv', 'json'],
  },

  'never-logged-in-users': {
    type: 'never-logged-in-users',
    name: 'Never Logged In Users',
    description: 'Users who have never logged into the system since account creation',
    category: 'User Activity',
    icon: 'user-delete',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNo', label: 'Phone', type: 'string', default: true },
      { id: 'role', label: 'Role', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: false },
      { id: 'accountCreatedAt', label: 'Account Created', type: 'date', default: true, sortable: true },
      { id: 'daysSinceCreation', label: 'Days Since Creation', type: 'number', default: true, sortable: true },
      { id: 'hasChangedPassword', label: 'Password Changed', type: 'boolean', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false },
      { id: 'studentActive', label: 'Student Record Active', type: 'boolean', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'role', label: 'Role', type: 'multiSelect', required: false, options: [
        { value: 'STUDENT', label: 'Student' },
        { value: 'TEACHER', label: 'Teacher' },
        { value: 'FACULTY_SUPERVISOR', label: 'Faculty Supervisor' },
        { value: 'PRINCIPAL', label: 'Principal' },
        { value: 'INDUSTRY', label: 'Industry' },
      ]},
      { id: 'createdAfter', label: 'Created After', type: 'date', required: false },
      { id: 'createdBefore', label: 'Created Before', type: 'date', required: false },
      { id: 'isActive', label: 'Account Status', type: 'select', required: false, options: [
        { label: 'Active Users', value: true },
        { label: 'Inactive Users', value: false },
      ]},
    ],
    groupBy: ['institutionName', 'role'],
    sortableColumns: ['userName', 'role', 'accountCreatedAt', 'daysSinceCreation'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'default-password-users': {
    type: 'default-password-users',
    name: 'Default Password Users',
    description: 'Users who have not changed their default password',
    category: 'User Activity',
    icon: 'key',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNo', label: 'Phone', type: 'string', default: true },
      { id: 'role', label: 'Role', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'accountCreatedAt', label: 'Account Created', type: 'date', default: true, sortable: true },
      { id: 'daysSinceCreation', label: 'Days Since Creation', type: 'number', default: true },
      { id: 'loginCount', label: 'Login Count', type: 'number', default: true },
      { id: 'lastLoginAt', label: 'Last Login', type: 'date', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: true },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false },
      { id: 'studentActive', label: 'Student Record Active', type: 'boolean', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'role', label: 'Role', type: 'multiSelect', required: false, options: [
        { value: 'STUDENT', label: 'Student' },
        { value: 'TEACHER', label: 'Teacher' },
        { value: 'FACULTY_SUPERVISOR', label: 'Faculty Supervisor' },
        { value: 'PRINCIPAL', label: 'Principal' },
        { value: 'INDUSTRY', label: 'Industry' },
      ]},
      { id: 'hasLoggedIn', label: 'Login Status', type: 'select', required: false, options: [
        { value: true, label: 'Has Logged In' },
        { value: false, label: 'Never Logged In' },
      ]},
      { id: 'isActive', label: 'Account Status', type: 'select', required: false, options: [
        { label: 'Active Users', value: true },
        { label: 'Inactive Users', value: false },
      ]},
    ],
    groupBy: ['institutionName', 'role'],
    sortableColumns: ['userName', 'role', 'accountCreatedAt', 'daysSinceCreation', 'loginCount'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'inactive-users': {
    type: 'inactive-users',
    name: 'Inactive Users Report',
    description: 'Users who have not logged in for a specified period',
    category: 'User Activity',
    icon: 'clock-circle',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNo', label: 'Phone', type: 'string', default: false },
      { id: 'role', label: 'Role', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'lastLoginAt', label: 'Last Login', type: 'date', default: true, sortable: true },
      { id: 'daysSinceLastLogin', label: 'Days Inactive', type: 'number', default: true, sortable: true },
      { id: 'loginCount', label: 'Total Logins', type: 'number', default: true },
      { id: 'accountCreatedAt', label: 'Account Created', type: 'date', default: false },
      { id: 'isActive', label: 'Account Active', type: 'boolean', default: true },
      { id: 'userActive', label: 'User Account Active', type: 'boolean', default: false },
      { id: 'studentActive', label: 'Student Record Active', type: 'boolean', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'role', label: 'Role', type: 'multiSelect', required: false, options: [
        { value: 'STUDENT', label: 'Student' },
        { value: 'TEACHER', label: 'Teacher' },
        { value: 'FACULTY_SUPERVISOR', label: 'Faculty Supervisor' },
        { value: 'PRINCIPAL', label: 'Principal' },
        { value: 'INDUSTRY', label: 'Industry' },
      ]},
      { id: 'inactiveDays', label: 'Inactive Period', type: 'select', required: false, options: [
        { value: 7, label: '7+ days' },
        { value: 14, label: '14+ days' },
        { value: 30, label: '30+ days' },
        { value: 60, label: '60+ days' },
        { value: 90, label: '90+ days' },
      ]},
      { id: 'isActive', label: 'Account Status', type: 'select', required: false, options: [
        { label: 'Active Accounts', value: true },
        { label: 'Inactive Accounts', value: false },
      ]},
    ],
    groupBy: ['institutionName', 'role'],
    sortableColumns: ['userName', 'role', 'lastLoginAt', 'daysSinceLastLogin', 'loginCount'],
    exportFormats: ['excel', 'csv', 'pdf', 'json'],
  },

  'user-audit-log': {
    type: 'user-audit-log',
    name: 'User Audit Log',
    description: 'Complete audit trail of user actions in the system',
    category: 'User Activity',
    icon: 'file-search',
    availableFor: ['STATE_DIRECTORATE', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'userName', label: 'User Name', type: 'string', default: true, sortable: true },
      { id: 'userRole', label: 'Role', type: 'string', default: true },
      { id: 'action', label: 'Action', type: 'string', default: true, sortable: true },
      { id: 'entityType', label: 'Entity Type', type: 'string', default: true },
      { id: 'entityId', label: 'Entity ID', type: 'string', default: false },
      { id: 'description', label: 'Description', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'ipAddress', label: 'IP Address', type: 'string', default: true },
      { id: 'userAgent', label: 'Browser/Device', type: 'string', default: false },
      { id: 'createdAt', label: 'Timestamp', type: 'date', default: true, sortable: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'userId', label: 'User', type: 'select', dynamic: true, required: false },
      { id: 'action', label: 'Action Type', type: 'multiSelect', required: false, options: [
        { value: 'LOGIN', label: 'Login' },
        { value: 'LOGOUT', label: 'Logout' },
        { value: 'CREATE', label: 'Create' },
        { value: 'UPDATE', label: 'Update' },
        { value: 'DELETE', label: 'Delete' },
        { value: 'VIEW', label: 'View' },
        { value: 'EXPORT', label: 'Export' },
        { value: 'PASSWORD_CHANGE', label: 'Password Change' },
      ]},
      { id: 'entityType', label: 'Entity Type', type: 'select', required: false, options: [
        { value: 'User', label: 'User' },
        { value: 'Student', label: 'Student' },
        { value: 'Internship', label: 'Internship' },
        { value: 'MonthlyReport', label: 'Monthly Report' },
        { value: 'Institution', label: 'Institution' },
      ]},
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['userName', 'action', 'entityType'],
    sortableColumns: ['userName', 'action', 'createdAt'],
    exportFormats: ['excel', 'csv', 'json'],
  },
};
